services:
  postgres:
    image: postgres:15
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pollsdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    networks:
      - backend
    ports:
      - 6379:6379

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - 9200:9200

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    networks:
      - backend
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    ports:
      - 5601:5601

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pollsapp-api:latest
    networks:
      - backend
    depends_on:
      - postgres
      - redis
      - opensearch
    ports:
      - 5232:5232
    environment:
      ConnectionStrings__PostgreSql: Host=postgres;Port=5432;Database=pollsdb;Username=postgres;Password=postgres
      ConnectionStrings__Redis: redis:6379,abortConnect=false,connectRetry=5,connectTimeout=5000
      ConnectionStrings__OpenSearch: http://opensearch:9200

      # JWT
      Jwt__Key: SUA_CHAVE_SUPER_SECRETA_MUITO_LONGA
      Jwt__Issuer: PollsApp
      Jwt__ExpireMinutes: 60
      # ASPNETCORE_ENVIRONMENT: Development

networks:
  backend:
    driver: bridge

volumes:
  pgdata: